
package com.sf.vas.mtnvtu.soapartifacts;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HostIFServicePortType", targetNamespace = "http://hostif.vtm.prism.co.za")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HostIFServicePortType {


    /**
     * 
     * @param part1
     * @return
     *     returns com.sf.vas.mtnvtu.soapartifacts.VendResponse
     */
    @WebMethod(action = "urn:vend")
    @WebResult(name = "vendResponse", targetNamespace = "http://hostif.vtm.prism.co.za/xsd", partName = "part1")
    public VendResponse vend(
        @WebParam(name = "vend", targetNamespace = "http://hostif.vtm.prism.co.za/xsd", partName = "part1")
        Vend part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.sf.vas.mtnvtu.soapartifacts.TransferResponse
     */
    @WebMethod(action = "urn:transfer")
    @WebResult(name = "transferResponse", targetNamespace = "http://hostif.vtm.prism.co.za/xsd", partName = "part1")
    public TransferResponse transfer(
        @WebParam(name = "transfer", targetNamespace = "http://hostif.vtm.prism.co.za/xsd", partName = "part1")
        Transfer part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.sf.vas.mtnvtu.soapartifacts.LookupResponse
     */
    @WebMethod(action = "urn:lookup")
    @WebResult(name = "lookupResponse", targetNamespace = "http://hostif.vtm.prism.co.za/xsd", partName = "part1")
    public LookupResponse lookup(
        @WebParam(name = "lookup", targetNamespace = "http://hostif.vtm.prism.co.za/xsd", partName = "part1")
        Lookup part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.sf.vas.mtnvtu.soapartifacts.ServiceResponse
     */
    @WebMethod(action = "urn:serviceRequest")
    @WebResult(name = "serviceResponse", targetNamespace = "http://hostif.vtm.prism.co.za/xsd", partName = "part1")
    public ServiceResponse serviceRequest(
        @WebParam(name = "serviceRequest", targetNamespace = "http://hostif.vtm.prism.co.za/xsd", partName = "part1")
        ServiceRequest part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.sf.vas.mtnvtu.soapartifacts.QueryTxResponse
     */
    @WebMethod(action = "urn:queryTx")
    @WebResult(name = "queryTxResponse", targetNamespace = "http://hostif.vtm.prism.co.za/xsd", partName = "part1")
    public QueryTxResponse queryTx(
        @WebParam(name = "queryTx", targetNamespace = "http://hostif.vtm.prism.co.za/xsd", partName = "part1")
        QueryTx part1);

}
