
package com.sf.vas.mtnvtu.soapartifacts;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HostIFService", targetNamespace = "http://hostif.vtm.prism.co.za", wsdlLocation = "file:/C:/Users/dawuzi/Documents/work/autotopup/service/HostIFService.wsdl")
public class HostIFService
    extends Service
{

    private final static URL HOSTIFSERVICE_WSDL_LOCATION;
    private final static WebServiceException HOSTIFSERVICE_EXCEPTION;
    private final static QName HOSTIFSERVICE_QNAME = new QName("http://hostif.vtm.prism.co.za", "HostIFService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/dawuzi/Documents/work/autotopup/service/HostIFService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HOSTIFSERVICE_WSDL_LOCATION = url;
        HOSTIFSERVICE_EXCEPTION = e;
    }

    public HostIFService() {
        super(__getWsdlLocation(), HOSTIFSERVICE_QNAME);
    }

    public HostIFService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HOSTIFSERVICE_QNAME, features);
    }

    public HostIFService(URL wsdlLocation) {
        super(wsdlLocation, HOSTIFSERVICE_QNAME);
    }

    public HostIFService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HOSTIFSERVICE_QNAME, features);
    }

    public HostIFService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HostIFService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HostIFServicePortType
     */
    @WebEndpoint(name = "HostIFServiceSOAP11port_http")
    public HostIFServicePortType getHostIFServiceSOAP11PortHttp() {
        return super.getPort(new QName("http://hostif.vtm.prism.co.za", "HostIFServiceSOAP11port_http"), HostIFServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HostIFServicePortType
     */
    @WebEndpoint(name = "HostIFServiceSOAP11port_http")
    public HostIFServicePortType getHostIFServiceSOAP11PortHttp(WebServiceFeature... features) {
        return super.getPort(new QName("http://hostif.vtm.prism.co.za", "HostIFServiceSOAP11port_http"), HostIFServicePortType.class, features);
    }

    /**
     * 
     * @return
     *     returns HostIFServicePortType
     */
    @WebEndpoint(name = "HostIFServiceSOAP12port_http")
    public HostIFServicePortType getHostIFServiceSOAP12PortHttp() {
        return super.getPort(new QName("http://hostif.vtm.prism.co.za", "HostIFServiceSOAP12port_http"), HostIFServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HostIFServicePortType
     */
    @WebEndpoint(name = "HostIFServiceSOAP12port_http")
    public HostIFServicePortType getHostIFServiceSOAP12PortHttp(WebServiceFeature... features) {
        return super.getPort(new QName("http://hostif.vtm.prism.co.za", "HostIFServiceSOAP12port_http"), HostIFServicePortType.class, features);
    }

    /**
     * 
     * @return
     *     returns HostIFServicePortType
     */
    @WebEndpoint(name = "HostIFServiceHttpport1")
    public HostIFServicePortType getHostIFServiceHttpport1() {
        return super.getPort(new QName("http://hostif.vtm.prism.co.za", "HostIFServiceHttpport1"), HostIFServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HostIFServicePortType
     */
    @WebEndpoint(name = "HostIFServiceHttpport1")
    public HostIFServicePortType getHostIFServiceHttpport1(WebServiceFeature... features) {
        return super.getPort(new QName("http://hostif.vtm.prism.co.za", "HostIFServiceHttpport1"), HostIFServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HOSTIFSERVICE_EXCEPTION!= null) {
            throw HOSTIFSERVICE_EXCEPTION;
        }
        return HOSTIFSERVICE_WSDL_LOCATION;
    }

}
