/**
 * 
 */
package com.sf.vas.mtnvtu.enums;

/**
 * @author dawuzi
 *
 */
public enum VtuVendStatusCode {

//    SUCCESS("0", "Successful"),
//    CANCELLED("1", "Cancelled"),
//    TIMEOUT("1", "Cancelled"),
//    SEQUENCE_ALREADY_EXISTS("106", "A transaction with the same sequence number already exist"),
    
    
    SUCCESSFUL("0", "Successful"),
    CANCELLED("1", "Cancelled"),
    TIMEOUT("2", "Timeout"),
    INVALID_REQUEST("8", "Invalid Request"),
    SEQUENCE_NUMBER_CHECK_FAILED("106", "Sequence Number Check Failed"),
    INVALID_ORIGINATOR_MSISDN("201", "Invalid Originator MSISDN"),
    INVALID_DESTINATION_MSISDN("202", "Invalid Destination MSISDN"),
    INSUFFICIENT_AIRTIME("301", "Insufficient Airtime"),
    INVALID_AIRTIME_AMOUNT("302", "Invalid Airtime Amount"),
    MSISDN_BARRED("1003", "MSISDN Barred"),
    INVALID_MSISDN("1004", "Invalid MSISDN"),
    TEMPORARY_INVALID_MSISDN("1007", "Temporary invalid MSISDN"),
    
    
//    system errors
    VENDING_TRANSFER_LIMIT_REACHED("319", "Vending Transfer Limit reached."),
    
    
    SERVER_ERROR("3", "Server Error"),
    SQL_ROLLBACK("4", "SQL Rollback"),
    PROGRESS_ERROR("5", "Progress Error"),
    PIN_REQUEST_TIMED_OUT("6", "PIN request timed out"),
    TEST("7", "Test"),
    PPAS_EXPIRED_VEND_SCRIPT_RESOLUTION("9", "Ppas Expired Vend script resolution"),
    QUERYTXNOTROLLEDBACK_SUCCESS("10", "QueryTxNotRolledBack success"),
    QUERYTXNOTROLLEDBACK_FAILURE("11", "QueryTxNotRolledBack failure"),
    ROLLBACKPPASFAILEDVENDS_SUCCESS("12", "RollbackPpasFailedVends success"),
    ROLLBACKPPASFAILEDVENDS_FAILURE("13", "RollbackPpasFailedVends failure"),
    TXRESOLVEDMANUALLY("14", "TxResolvedManually"),
    QUERYCASE497VENDS_SCRIPT_RESOLUTION("15", "QueryCase497Vends script resolution"),
    RESERVED("16", "RESERVED"),
    RESERVED2("17", "RESERVED"),
    RESERVED3("18", "RESERVED"),
    RESERVED4("19", "RESERVED"),
    RESERVED5("20", "RESERVED"),
    GENERAL_TX_ERROR("21", "General Tx Error"),
    MOBILE_MONEY_ERROR("22", "Mobile Money Error"),
    MAC_VERIFICATION_FAILED("101", "MAC Verification Failed"),
    PIN_VERIFICATION_FAILED("102", "PIN Verification Failed"),
    PIN_RETRIES_EXCEEDED("103", "PIN Retries Exceeded"),
    PIN_VALIDITY_PERIOD_EXPIRED("104", "PIN Validity Period Expired"),
    VELOCITY_CHECK_FAILED("105", "Velocity Check Failed"),
    VENDOR_NOTIFICATION_FAILED("107", "Vendor Notification Failed"),
    SUBSCRIBER_NOTIFICATION_FAILED("108", "Subscriber Notification Failed"),
    PIN_REQUEST_FAILED("109", "PIN request failed"),
    INVALID_AUTHENTICATION_CODE_LENGTH("110", "Invalid authentication code length"),
    INVALID_AUTHENTICATION_CODE("111", "Invalid authentication code"),
    AUTH_CODE_SENT_TO_DEVICE("112", "Auth code sent to device"),
    DESTINATION_ALREADY_LINKED("203", "Destination already Linked"),
    DESTINATION_ALREADY_UNLINKED("204", "Destination already unlinked"),
    SUB_DISTRIBUTOR_LEVELS_EXCEEDED("205", "Sub-distributor levels exceeded"),
    STAFF_CANNOT_LOGON_TO_VTM_INTERNET("206", "Staff cannot logon to vtm internet"),
    ONLY_STAFF_CAN_LOGON_TO_VTM_INTRANET("207", "Only staff can logon to vtm intranet"),
    INVALID_PASSWORD("208", "Invalid Password"),
    MSISDN_ALREADY_REGISTERED("209", "Msisdn already registered"),
    MSISDN_ALREADY_DEREGISTERED("210", "Msisdn already deregistered"),
    INVALID_DEREGISTRATION("211", "Invalid deregistration"),
    SUSPENDED("212", "Suspended"),
    PRINCIPAL_TREE_CRITERIA_FAILED("213", "Principal tree criteria failed"),
    TARIFF_LIST_DEPENDENCY("214", "Tariff List dependency"),
    TARIFF_GROUP_DEPENDENCY("215", "Tariff Group dependency"),
    INVALID_LINK("303", "Invalid Link"),
    TRANSACTION_LIMIT_EXCEEDED("304", "Transaction Limit Exceeded"),
    DAILY_LIMIT_EXCEEDED("305", "Daily Limit Exceeded"),
    INVALID_TRANSFER("306", "Invalid Transfer"),
    INVALID_VENDOR_PROMOTION("307", "Invalid vendor promotion"),
    INVALID_ORIGIN_ACCOUNT("308", "Invalid origin account"),
    INVALID_DESTINATION_ACCOUNT("309", "Invalid destination account"),
    INVALID_TARIFF_CLASS("310", "Invalid Tariff class"),
    TRANSFER_ACCOUNT_UNLINK_BALANCE_CRITERIA_FAILED("311", "Transfer Account unlink balance criteria failed"),
    VEND_ACCOUNT_UNLINK_BALANCE_CRITERIA_FAILED("312", "Vend Account unlink balance criteria failed"),
    MINIMUM_TRANSFER_CRITERIA_FAILED("313", "Minimum transfer criteria failed"),
    MAXIMUM_TRANSFER_CRITERIA_FAILED("314", "Maximum transfer criteria failed"),
    TRANSFER_INCREMENT_CRITERIA_FAILED("315", "Transfer increment criteria failed"),
    ZERO_ACCOUNT_BALANCE_CRITERIA_FAILED("316", "Zero account balance criteria failed"),
    INVALID_PARAMETERS("317", "Invalid parameters"),
    MINIMUM_TRANSFER_CRITERIA_PER_LEVEL_FAILED("318", "Minimum transfer criteria per level failed"),
    INVALID_SESSIONREF_FOR_THIS_WEB_SHIFT("320", "Invalid sessionRef for this web shift"),
    INVALID_LINK_VEND_ACCOUNT_BALANCE_MUST_BE_ZERO("321", "Invalid Link. Vend account balance must be zero"),
    INVALID_CRITERIA_FOR_VENDOR_VA_TO_VA_TRANSFER("322", "Invalid Criteria for Vendor VA to VA Transfer"),
    ECHARGE_VENDOR_VA_TO_VA_TRANSFER_DISABLED("323", "eCharge Vendor VA to VA Transfer Disabled"),
    ECHARGE_BALANCE_DISABLED("324", "eCharge Balance Disabled"),
    ECHARGE_STATEMENT_DISABLED("325", "eCharge Statement Disabled"),
    ECHARGE_STATEMENT_FAILURE("326", "eCharge Statement Failure"),
    INVALID_STAFF_REGISTRATION("327", "Invalid Staff Registration"),
    UPDATE_PARTNER_STATUS("328", "Update Partner Status"),
    INVALID_LINK_THIS_IS_A_VENDOR_ONLY_SIM("329", "Invalid Link. This is a Vendor only SIM"),
    WAITING_FOR_AUTHORIZATION("401", "Waiting For Authorization"),
    WAITING_FOR_NEW_PIN_ENTRY("402", "Waiting for new PIN Entry"),
    WAITING_FOR_AA_ACCEPTANCE("403", "Waiting For AA Acceptance"),
    WAITING_FOR_VENDOR_NOTIFICATION("404", "Waiting for vendor notification"),
    WAITING_FOR_SUBSCRIBER_NOTIFICATION("405", "Waiting for subscriber notification"),
    REQUEST_REJECTED("406", "Request Rejected"),
    PENDING_PPAS_CREDIT("407", "Pending PPAS Credit"),
    AUTHORIZATION_BYPASSED_FOR_OPEN_SHIFT("408", "Authorization bypassed for open shift"),
    WAITING_FOR_ADM_RESPONSE("409", "Waiting for ADM Response"),
    WAITING_FOR_USER_ACCEPTANCE("410", "Waiting for user acceptance"),
    WAITING_FOR_BATCH_UNLINK_PROCESS_TO_OCCUR("412", "Waiting for batch unlink process to occur"),
    FUNCTIONALITY_NOT_SUPPORTED("413", "Functionality not supported"),
    REPORT_REQUEST_PENDING("414", "Report Request Pending"),
    BYPASSING_ORIGINATOR_NOTIFICATION("415", "Bypassing originator notification"),
    BYPASSING_DESTINATION_NOTIFICATION("416", "Bypassing destination notification"),
    ERROR_SUB_DISTRIBUTOR_MUST_UNLINK_AGENTS("417", "Error Sub distributor must unlink agents"),
    UNLINKED_FROM_PRINCIPLE("418", "Unlinked from principle"),
    VENDOR_PROMOTION_TO_DISTRIBUTOR("419", "Vendor promotion to distributor"),
    SUB_DISTR_PROMOTION_TO_DISTRIBUTOR("420", "Sub distr promotion to distributor"),
    INVALID_PHONE_REGISTRATION("421", "Invalid Phone Registration"),
    WAITING_FOR_MOBILE_MONEY_ACCEPTANCE("422", "Waiting for Mobile Money acceptance"),
    MOBILE_MONEY_ACCOUNT_NOT_LOCKED("423", "Mobile Money Account not locked"),
    LOGIN_IN_USE("501", "Login in use"),
    LOGIN_SUSPENDED("502", "Login suspended"),
    LOGIN_TERMINATED("503", "Login terminated"),
    LOGIN_IN_USE_BY_J2ME_DEVICE("504", "Login in use by J2me device"),
    LOGIN_IN_USE_BY_WEB_CLIENT("505", "Login in use by web client"),
    DESTINATION_PRINCIPAL_NOT_ACTIVE("550", "Destination principal not active"),
    DESTINATION_PRINCIPAL_NOT_SUB_DISTRIBUTOR("551", "Destination principal not sub/distributor"),
    START_OF_TRANSACTION("601", "Start of transaction"),
    PIN_MAC_VERIFIED("602", "Pin/mac verified"),
    IMSI_RECEIVED_FROM_STK("603", "Imsi Received from STK"),
    DEBIT_ROLLED_BACK("604", "Debit rolled back"),
    PIN_REQUEST_RESENT("605", "PIN Request Resent"),
    CREDIT_COMMITTED("606", "Credit committed"),
    PPAS_CREDITED("607", "Ppas Credited"),
    PPAS_ROLLED_BACK("608", "Ppas rolled back"),
    NOTHING_TO_ROLLBACK("609", "Nothing to rollback"),
    ROLLBACK_WOULD_CAUSE_A_NEGATIVE_SUSPENDED_BALANCE("610", "Rollback would cause a negative suspended balance"),
    USER_REJECTED("611", "User Rejected"),
    TRANSACTION_SCHEDULED_FOR_PROCESSING("612", "Transaction scheduled for processing"),
    DUPLICATE_ROLLBACK("613", "Duplicate Rollback"),
    USSD_NOT_VTU_USER("620", "Ussd: Not Vtu User"),
    USSD_REGISTERED("621", "Ussd: Registered"),
    USSD_NOT_REGISTERED("622", "Ussd: Not Registered"),
    USSD_DISABLED("623", "Ussd: Disabled"),
    USSD_SUSPENDED("624", "Ussd: Suspended"),
    USSD_PASSWORD_REGISTERED("625", "Ussd: Password Registered"),
    USSD_PASSWORD_VALIDATED("626", "Ussd: Password Validated"),
    USSD_PASSWORD_INCORRECT("627", "Ussd: Password Incorrect"),
    USSD_PASSWORD_RETRIES_EXCEEDED("628", "Ussd: Password Retries Exceeded"),
    USSD_PASSWORD_RESET_REQUESTED("629", "Ussd: Password Reset Requested"),
    USSD_PASSWORD_EXPIRED("630", "Ussd: Password Expired"),
    USSD_ONLY_VENDOR_ALLOW("631", "Ussd: Only Vendor allow"),
    USSD_PIN_REQUEST("632", "Ussd: Pin request"),
    USSD_DIST_TREE_DISABLED("633", "Ussd: Dist Tree Disabled"),
    USSD_PASSWORD_SAME_AS_CURRENT("634", "Ussd: Password same as current"),
    USSD_ONLY_DELEGATES_ALLOWED("635", "Ussd: Only Delegates allowed"),
    COMMS_MANAGER_TIMEOUT("701", "Comms Manager Timeout"),
    INCORRECT_RESPONSE_FROM_COMMS_MANAGER("702", "Incorrect Response From Comms Manager"),
    ERROR_RECEIVED_FROM_COMMS_MANAGER("703", "Error Received From Comms Manager"),
    CONNECTION_ERROR_TO_COMMS_MANAGER("704", "Connection Error to Comms Manager"),
    CRYPTO_ERROR("705", "Crypto Error"),
    VTU_PIN_MISMATCH("706", "VTU Pin mismatch"),
    DUPLICATE_MESSAGE_RECEIVED_IGNORE("707", "Duplicate message received, ignore"),
    VTU_PIN_EXPIRED("708", "VTU PIN expired"),
    VTU_PIN_DISABLED("709", "VTU PIN disabled"),
    VTU_PIN_ALREADY_USED("710", "VTU PIN already used"),
    VTU_PIN_COPY_ERROR("711", "VTU PIN copy error"),
    MSISDN_LENGTH_ERROR("712", "Msisdn length error"),
    AUTHCODE_NOT_LINKED_TO_MSISDN("713", "AuthCode not linked to MSISDN"),
    SESSION_DOES_NOT_EXIST("714", "Session does not exist"),
    WEB_SHIFT_OPEN("801", "Web shift open"),
    WEB_SHIFT_LOCKED("802", "Web shift locked"),
    WEB_SHIFT_CLOSED("803", "Web shift closed"),
    NO_WEB_SHIFT_AVALIABLE("804", "No web shift avaliable"),
    WAITING_FOR_AUTHENTICATION_CODE_TO_BE_RECEIVED("806", "Waiting for Authentication code to be received"),
    OPENING_WEB_SHIFT("807", "Opening Web Shift"),
    USER_PRE_PROVISIONED("901", "User pre provisioned"),
    LICENCE_REGISTRATION_THRESHOLD_ALERT("910", "Licence Registration Threshold Alert"),
    THE_LICENCE_LIMIT_IS_ABOUT_TO_BE_BREACHED("911", "The licence limit is about to be breached"),
    VTU_LICENCE_DOES_NOT_ALLOW_USER_REGISTRATION("912", "VTU Licence does not allow user registration."),
    DEFAULT_PPAS_ERROR_MESSAGE_IF_NO_MAPPING_IS_FOUND("1000", "Default PPAS error message if no mapping is found"),
    PPAS_FAILED("1001", "PPAS Failed"),
    NO_CONNECTION_AVAILABLE_TO_PPAS("1002", "No Connection Available to PPAS"),
    INCORRECT_ACTIVATION("1005", "Incorrect activation"),
    ALREADY_LOADED("1006", "Already loaded"),
    INVALID_TRANSACTION("1008", "Invalid transaction"),
    RE_ENTER_TRANSACTION("1009", "Re-enter transaction"),
    FORMAT_ERROR("1010", "Format Error"),
    DUPLICATE_PAYMENT("1011", "Duplicate payment"),
    SERVICE_EXPIRED("1012", "Service Expired"),
    MAXIMUM_AMOUNT_EXCEEDED_FOR_DAILY_RECHARGE("1013", "Maximum amount exceeded for daily recharge"),
    MAXIMUM_AMOUNT_EXCEEDED_FOR_WEEKLY_RECHARGE("1014", "Maximum amount exceeded for weekly recharge"),
    INVALID_MESSAGE_LENGTH("1050", "Invalid Message Length"),
    INVALID_MESSAGE_PROTOCOL("1051", "Invalid Message Protocol"),
    INVALID_IDENTIFICATION_TYPE("1052", "Invalid Identification Type"),
    INVALID_NIT("1053", "Invalid NIT"),
    INVALID_CONTROL_NUMBER("1054", "Invalid Control Number"),
    INVALID_COMMERCE_CODE("1055", "Invalid Commerce Code"),
    WHOLESALER_DEBIT_FAILED("1060", "Wholesaler Debit Failed"),
    NO_CELL_CHARGES_IN_LAST_MONTH("1061", "No Cell Charges In Last Month"),
    AUTHENTICATION_ERROR("1070", "Authentication Error"),
    MTNRAC_DEFAULT_MTNRAC_ERROR_MESSAGE("1100", "MTNRAC: Default MTNRAC error message"),
    MTNRAC_NOT_CONNECTED("1101", "MTNRAC: Not connected"),
    MTNRAC_MSISDN_IS_NOT_A__POST_PAID_SUBSCRIBER("1102", "MTNRAC: Msisdn is not a  post-paid subscriber"),
    POSTPAID_PAYMENT_DUPLICATED("1103", "Postpaid: Payment duplicated"),
    VOUCHER_OUT_OF_STOCK("1200", "Voucher: Out of stock"),
    VOUCHER_INVALID_PRODUCT("1201", "Voucher: Invalid product"),
    LANGUAGE_CHANGE_SUCCESS("1300", "Language: Change Success"),
    LANGUAGE_CHANGE_FAILURE("1310", "Language: Change Failure"),
    TXQUERY_SUCCESS("1400", "TxQuery Success"),
    TXQUERY_SUCCESS_TRANSFER("1401", "TxQuery Success: Transfer"),
    TXQUERY_SUCCESS_VEND("1402", "TxQuery Success: Vend"),
    TXQUERY_SUCCESS_IFSCREDIT("1403", "TxQuery Success: IFSCredit"),
    TXQUERY_FAILURE("1410", "TxQuery: Failure"),
    ENDOFDAY_SUCCESS("1500", "EndOfDay Success"),
    ENDOFDAY_SUCCESS_HEADER("1501", "EndOfDay Success:Header"),
    ENDOFDAY_SUCCESS_HEADERTRANSFER("1502", "EndOfDay Success:HeaderTransfer"),
    ENDOFDAY_SUCCESS_BODYTRANSFER("1503", "EndOfDay Success:BodyTransfer"),
    ENDOFDAY_SUCCESS_HEADERVEND("1504", "EndOfDay Success:HeaderVend"),
    ENDOFDAY_SUCCESS_BODYVEND("1505", "EndOfDay Success:BodyVend"),
    ENDOFDAY_FAILURE("1510", "EndOfDay Failure"),
    NOT_RETRIEVED_BY_VTM("2000", "Not Retrieved By VTM"),
    RETRIEVED_BY_VTM("2001", "Retrieved By VTM"),
    OPERATOR_REJECTED("2002", "Operator Rejected"),
    OPERATOR_ACCEPTED("2003", "Operator Accepted"),
    INVALID_IFS_SIGNATURE("2004", "Invalid IFS signature"),
    INVALID_DISTRIBUTOR_FOR_CREDIT("2005", "Invalid Distributor for credit"),
    FAILED_TO_UPDATE_IFS("2006", "Failed to update IFS"),
    ACCEPTED_BY_VTM("2007", "Accepted by VTM"),
    INVALID_IFS_CREDIT("2008", "Invalid Ifs Credit"),
    ERROR_CALLING_GETDISTRIBUTORS("2009", "Error calling getDistributors"),
    ERROR_CALLING_GETAIRTIMECREDITS("2010", "Error calling getAirtimeCredits"),
    ERROR_READING_GETDISTRIBUTORS_RESULTSET_COLUMN("2011", "Error reading getDistributors ResultSet column"),
    ERROR_READING_GETAIRTIMECREDITS_RESULTSET_COLUMN("2012", "Error reading getAirtimeCredits ResultSet column"),
    ERROR_NO_ACTIVE_KEY_FOUND_FOR_OPERATOR("2013", "Error no active key found for operator"),
    INVALID_IFS_SEQUENCE_NUMBER("2014", "Invalid IFS sequence number"),
    DUPLICATE_DISTRIBUTOR("2015", "Duplicate Distributor"),
    DUPLICATE_IFS_TRANSACTIONID("2016", "Duplicate Ifs TransactionId"),
    NO_REGISTRATION_EXISTS_FOR_THIS_UPDATE("2017", "No registration exists for this update"),
    THIS_IFS_TRANSACTION_HAS_ALREADY_BEEN_PROCESSED("2018", "This ifs transaction has already been processed"),
    COULD_NOT_SEND_NEW_PIN_REQUEST_SMS("2019", "Could not send new pin request SMS"),
    IFS_USER_ERROR("2020", "IFS User Error"),
    IFS_SYSTEM_FAILURE("2021", "IFS System Failure"),
    IFS_QUEUED("2022", "IFS Queued"),
    IFS_OUTSIDE_OF_SLA_TIMES("2023", "IFS Outside of SLA times"),
    IFS_UNAVAILABLE_DUE_TO_MAINTENANCE("2024", "IFS Unavailable due to maintenance"),
    IFS_UNDEFINED("2025", "IFS Undefined"),
    IFS_INVALID_PARTNER_PROMOTION("2026", "IFS Invalid partner promotion"),
    USER_SIM_NOT_ACTIVATED_YET("2027", "User sim not activated yet"),
    COMMS_ERROR_ON_PROVISIONING_INTERFACE("2028", "Comms error on provisioning interface"),
    SELF_REGISTER_NEW_VENDOR_CREATED("2029", "Self register. New vendor created"),
    SELF_REGISTER_SUB_DISTR_MIGRATED_TO_VENDOR("2030", "Self register. Sub-Distr migrated to vendor"),
    SELF_REGISTER_NO_CHANGES_TO_PARTNER_TYPE("2031", "Self register. No changes to partner type"),
    THIS_IS_A_VENDOR_ONLY_APPLICATION("2032", "This is a vendor only application"),
    SIMSWAP_TO_NEW_VENDOR_REGISTRATION("2033", "SimSwap to new Vendor registration"),
    USER_LOGIN_STATUS_WAS_UPDATED("2500", "User Login status was updated"),
    NO_VALID_USER_STATUS_WAS_FOUND_TO_UPDATE_UPDATED("2501", "No valid user status was found to update updated"),
    AA_ALREADY_EXISTS("3000", "AA already exists"),
    AA_NOT_FOUND_IN_DB("3001", "AA not found in db"),
    AA_VERIFICATION_FAILED("3002", "AA verification failed"),
    PIN_DOES_NOT_EXIST_IN_DB("3003", "PIN does not exist in db"),
    SIM_NOT_ACTIVE("3004", "SIM not active"),
    MAC_ERROR("3005", "MAC error"),
    COUNTER_ERROR("3006", "Counter error"),
    CONNECTION_ERROR("3007", "Connection error"),
    SIM_NOT_ACTIVE_NULL_ICCID("3008", "SIM not active (NULL ICCID)"),
    SIM_NOT_ACTIVE_INVALID_STATUS("3009", "SIM not active (invalid status)"),
    DUKPT_COUNTER_ERROR("3010", "DUKPT Counter error"),
    DUKPT_COUNTER_ERROR2("3011", "DUKPT Counter error"),
    NEW_AA_REQUESTED("3012", "New AA requested"),
    MSISDN_CHANGE_FAILED("3013", "Msisdn change failed"),
    SEND_NEW_AUTH_CODE("3014", "Send New Auth Code"),
    SEND_NEW_AA("3015", "Send New AA"),
    BONUS_PROCESSING_FAILURE("4000", "Bonus Processing Failure"),
    BONUS_PROCESSING_FAILURE2("4001", "Bonus Processing Failure"),
    BONUS_PROCESSING_FAILURE3("4002", "Bonus Processing Failure"),
    BONUS_PROCESSING_FAILURE4("4003", "Bonus Processing Failure"),
    BONUS_PROCESSING_FAILURE5("4004", "Bonus Processing Failure"),
    BONUS_PROCESSING_FAILURE6("4005", "Bonus Processing Failure"),
    BONUS_PROCESSING_SUCCESS7("4006", "Bonus Processing Success"),
    RAC_TRANSACTIONS_NOT_ALLOWED("5000", "RAC transactions not allowed"),
    HOSTIF_GENERAL_ERROR("6000", "HostIF General Error"),
    NOT_A_VALID_HOSTIF_USER("6001", "Not a valid HostIF user"),
    VOUCHER_GENERATE("8501", "Voucher Generate"),
    VOUCHER_GENERATION_FAILURE("8502", "Voucher Generation Failure"),
    VOUCHER_UPDATE_SUCCESS("8503", "Voucher Update Success"),
    VOUCHER_UPDATE_FAILURE("8504", "Voucher Update Failure"),
    USAT_APPLICATION_LANGUAGE_CHANGE_SUCCEEDED("9001", "USAT application language change succeeded"),
    USAT_APPLICATION_LANGUAGE_CHANGE_FAILED("9002", "USAT application language change failed"),
    SAT_GENERAL_ERROR("10001", "Sat General Error"),
    SAT_HTTP_408_ERROR("10002", "Sat HTTP 408 Error"),
    SAT_HTTP_500_ERROR("10003", "Sat HTTP 500 Error"),
    INVALID_BULK_FILE_FORMAT("12001", "Invalid bulk file format"),
    INVALID_BULK_TRANSACTION_TYPE("12002", "Invalid bulk transaction type"),
    DUPLICATE_BULK_REFERENCE("12003", "Duplicate bulk reference"),
    BULK_COUNT_DOES_NOT_MATCH_THE_TAIL_RECORD("12004", "Bulk count does not match the tail record"),
    INVALID_HEAD_RECORD("12005", "Invalid Head Record"),
    INVALID_DETAIL_RECORD("12006", "Invalid Detail Record"),
    INVALID_TAIL_RECORD("12007", "Invalid Tail Record"),
    INVALID_BULK_TRANSACTION_AUTHORIZER_MSISDN("12008", "Invalid Bulk transaction authorizer msisdn"),
    INVALID_RECORD_TYPE("12009", "Invalid Record Type"),
    MAXIMUM_TRANSACTIONS_PER_BULK_REQUEST_EXCEEDED("12010", "Maximum transactions per bulk request exceeded"),
    PPAS_QUOTA_REACHED("12011", "PPAS Quota Reached"),
    CANNOT_VEND_TO_DIFFERENT_DISTRIBUTORREF("12012", "Cannot Vend to different DistributorRef"),
//    SUCCESS("14201", "Success"),
    UNKOWN_ERROR("14202", "Unkown Error"),
    FAILED("14203", "Failed"),
    INVALID_SERVICE_ID("14204", "Invalid Service ID"),
    INVALID_SERVICE_CODE("14205", "Invalid Service Code"),
    ACTIVE_SUBSCRIPTION_ALREADY_EXISTS("14206", "Active Subscription Already Exists"),
    SYSTEM_UNAVAILABLE("14207", "System Unavailable"),
//    SERVER_ERROR("14208", "Server Error"),
    ;
    
    private String responseCode;
    private String responseDescription;

    private VtuVendStatusCode(String responseCode, String responseDescription) {
        this.responseCode = responseCode;
        this.responseDescription = responseDescription;
    }

	public String getResponseCode() {
        return responseCode;
    }

    public String getResponseDescription() {
        return responseDescription;
    }
	
	public static VtuVendStatusCode from(String code){
		for(VtuVendStatusCode val : values()){
			if(val.getResponseCode().equals(code)){
				return val;
			}
		}
		return null;
	}
}
